# Error Handling

Despite what browsing the modern web may have you believe, infinite spinners is not an adequate error handling strategy.

The first line of defense, as we've seen, is to throw an error in the queryFn.
In fact, whether you throw an error, call the reject method for a manually-constructed promise, or return the results of Promise.reject() â€“ any promise rejection tells React Query that an error occurred and to set the status of the query to error.

```ts
function useRepos() {
  return useQuery({
    queryKey: ['repos'],
    queryFn: async () => {
      const response = await fetch('https://api.github.com/orgs/TanStack/repos')
      
      if (!response.ok) {
        throw new Error(`Request failed with status: ${response.status}`)
      }

      return response.json()
    },
  })
}
```

## Using Try/Catch to handle Error

Now there may come a time when you need to debug or wrap the response of your fetch request inside of your queryFn. To do this, you may be tempted to manually catch the error yourself.
By catching the error yourself, unless you throw it again inside of the catch block, you're effectively swallowing the error, preventing it from making its way up to React Query.
This has a number of downsides, the most obvious being that React Query won't know that an error occurred and therefore, won't be able to update the status of the query correctly.

A less obvious downside is that React Query also won't know that it should retry the request again. In fact, __by default, when a request fails, React Query will perform 3 retries__, using an exponential backoff algorithm to determine how long to wait between each one.
This means each attempt is exponentially longer than the previous, starting with a delay of 1 second and maxing out at 30 seconds.

```ts
function useRepos() {
  return useQuery({
    queryKey: ['repos'],
    queryFn: async () => {
      try {
        const response = await fetch('https://api.github.com/orgs/TanStack/repos')
        
        if (!response.ok) {
          throw new Error(`Request failed with status: ${response.status}`)
        }

        return response.json()
      } catch (e) {
        console.log("Error: ", e)
      }
    },
  })
}

```

## retry & retryDelay

as most things with React Query, this default behavior is completely customizable via the retry and retryDelay options.

__retry__ tells React Query __how many times to retry the request__, and __retryDelay__ tells it __how long to wait between each failed attempt__.

So in the code below, React Query will retry the request 5 times, with a delay of 5000 milliseconds between each attempt.

```ts
useQuery({
  queryKey: ['repos'],
  queryFn: fetchRepos,
  retry: 5,
  retryDelay: 5000,
})
```

If you need even more granular control, you can pass a function to both options and they'll receive the failureCount and the error as arguments that you can use to derive your values.
So for example, if we wanted to provide our own custom algorithm for the delay between retries as well as only retrying an error that has a status code in the 5xx range, we could do something like this.
And while these retries are happening, the query will remain in a _pending_ state.
React Query will include the _failureCount_ and _failureReason_ properties in the object that useQuery returns.
Additionally, both values will be reset as soon as the query goes into a success state.
These values give you the flexibility to update your UI in the event of a failed data request. For example, you could display a message to the user that the request is taking longer than expected, or even get cute with it and show them how many requests you've tried to make.

```ts
useQuery({
  queryKey: ['repos'],
  queryFn: fetchRepos,
  retry: (failureCount, error) => {
    if (error instanceof HTTPError && error.status >= 500) {
      return failureCount < 3
    }

    return false
  },
  retryDelay: (failureCount) => failureCount * 1000,
})

```

## modifying retry and retryDelay initially

```ts
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 5,
      retryDelay: 5000,
    },
  },
})
```

## throwOnError

If you need even more control over how or which errors are thrown, you can pass a function to throwOnError.

If the function returns true, the error will be thrown to the ErrorBoundary. Otherwise, it won't.
So for example, the downside of our current implementation is that all errors will be thrown to the ErrorBoundary, even ones that occur during background refetches.

Most likely, if the user already has data and a background refetch fails, we want it to fail silently. To do that, we can return true from throwOnError if query.state.data is undefined.
Or if you only wanted errors in the 5xx range to be thrown to the ErrorBoundary, you could do something like this.

```ts
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      throwOnError: (error, query) => {
        return typeof query.state.data === 'undefined'
      }
    }
  },
  queryCache: new QueryCache({
    onError: (error, query) => {
      if (typeof query.state.data !== 'undefined') {
        toast.error(error.message)
      }
    }
  })
})```